decorateSlides();
const deck=document.querySelector('#deck');
const clean=s=>s.replace(/<br>/g,' ');
function flowHTML(){return `<div class="flow" aria-label="गीता की विचार-यात्रा">${stages.map((s,i)=>`<button class="flow-step" data-jump="${s.jump}" aria-label="चरण ${String(i+1).padStart(2,'0')}: ${s.title}. ${s.idea}"><span class="num">${String(i+1).padStart(2,'0')}</span><h2>${s.title}</h2><p>${s.idea}</p><small><b>वक्ता संकेत</b>${s.cue}</small></button>`).join('')}</div>`}
function visualHTML(s){if(s.visual==='identity')return `<div class="equation"><div class="equation-row"><span class="token">है</span><span class="operator">+</span><span class="token">यह</span><span class="operator">=</span><span class="token hot">मैं हूँ</span></div><div class="cascade"><div>“मैं हूँ” से कर्तापन</div><div>कर्तापन से फलाकांक्षा</div><div>फलाकांक्षा से भय</div><div>भय से बंधन</div></div></div>`;if(s.visual==='desire')return `<div class="cascade light"><div>चाह की पूर्ति के लिए कर्म</div><div>अपेक्षा से चिंता</div><div>पाने की आशा · खोने का भय</div><div>मोह और पराश्रय</div></div>`;if(s.visual==='witness')return `<div class="witness"><span class="orbit o1">शरीर</span><span class="orbit o2">विचार</span><span class="orbit o3">भावना</span><span class="orbit o4">भूमिका</span><div class="witness-ring"><div class="witness-core"><span>दृश्य</span><strong>द्रष्टा</strong><span>परिवर्तन को जानने वाला</span></div></div></div>`;if(s.visual==='routes')return `<div class="fork"><div class="route"><span class="route-tag">भोगमार्ग</span><h3>जो है, वह छूटे नहीं।</h3><p>जो नहीं है, वह मिल जाए।<br>केंद्र: “मैं” की सुरक्षा और तुष्टि</p></div><div class="route yoga"><span class="route-tag">योगमार्ग</span><h3>“मैं” की खोज</h3><p>दृश्य से द्रष्टा की ओर।<br>दिशा: “मैंपन” का त्याग</p></div></div>`;if(s.visual==='equanimity')return `<div class="pair-grid">${['लाभ ↔ हानि','यश ↔ अपयश','प्रिय ↔ अप्रिय','सिद्धि ↔ असिद्धि'].map(x=>`<div>${x}</div>`).join('')}</div><div class="final-line">क्रिया प्रकृति में;<br>स्थिति सत्य में।</div>`;if(s.visual==='doer')return `<div class="axis"><div class="axis-card"><strong>प्रकृति</strong><span>गुणों द्वारा कर्म होते हैं</span></div><div class="axis-arrow">→</div><div class="axis-card"><strong>अहंकार</strong><span>“मैं कर्ता हूँ” की मान्यता</span></div></div><div class="pathline"><span>गुण</span><span>कर्म</span><span>कर्ता की मान्यता</span><span>आसक्ति</span><span>बंधन</span></div>`;return ''}
function content(s){return `${s.type==='flow'?flowHTML():''}${s.visual?visualHTML(s):''}${s.quote?`<blockquote>${s.quote}</blockquote>`:''}${s.verse?`<div class="verse-strip"><div class="sanskrit">${s.verse}</div><div class="ref">${s.ref}</div></div>`:''}${s.pairs?`<div class="pairs">${s.pairs.map(p=>`<div class="pair"><h2>${p[0]}</h2><p>${p[1]}</p></div>`).join('')}</div>`:''}${s.lead?`<p class="lead">${s.lead}</p>`:''}${s.items?(s.type==='chain'?`<div class="chain-list">${s.items.map(x=>`<div class="chain-item">${x}</div>`).join('')}</div>`:`<ul class="items">${s.items.map(x=>`<li>${x}</li>`).join('')}</ul>`):''}${s.timer?`<div class="timer"><output>${format(s.timer)}</output><button data-timer="${s.timer}">चिंतन टाइमर शुरू</button><button data-reset="${s.timer}">रीसेट</button></div>`:''}`}
function format(t){return `${Math.floor(t/60).toString().padStart(2,'0')}:${(t%60).toString().padStart(2,'0')}`}
deck.innerHTML=slides.map((s,i)=>`<section class="slide ${s.type==='flow'?'flow-slide':s.type||''} ${s.layout}" data-word="${s.word}" aria-label="${i+1}. ${clean(s.title)}"><div class="eyebrow"><span class="chapter">${s.section}</span>${s.en}</div><div class="slide-content"><h1>${s.title}</h1><div class="body-copy">${content(s)}</div></div><div class="slide-footer"><span>${s.ref||'गीता और नेतृत्व'}</span><span class="folio">${String(i+1).padStart(2,'0')} / ${slides.length}</span></div></section>`).join('');
let current=0,tick=null,remaining=0,activeTimer=null;const panel=document.querySelector('#panel');
function stopTimer(){clearInterval(tick);tick=null;if(activeTimer)activeTimer.querySelector('[data-timer]').textContent='टाइमर जारी रखें';}
function show(n){stopTimer();current=Math.max(0,Math.min(slides.length-1,n));document.querySelectorAll('.slide').forEach((s,i)=>{s.classList.toggle('active',i===current);s.setAttribute('aria-hidden',String(i!==current));});document.querySelector('#counter').textContent=`${current+1} / ${slides.length}`;document.querySelector('#section').textContent=slides[current].section;document.querySelector('#progress').style.width=`${(current+1)/slides.length*100}%`;document.querySelector('#prev').disabled=current===0;document.querySelector('#next').disabled=current===slides.length-1;history.replaceState(null,'',`#${current+1}`);window.scrollTo(0,0)}
function dialog(html){document.querySelector('#panel-content').innerHTML=html;panel.showModal()}
function notes(){const s=slides[current];dialog(`<p class="eyebrow">FACILITATOR NOTES · SLIDE ${current+1}</p><h2>${s.title}</h2><p>समय: ${s.time||'संक्रमण / पिछले खंड में शामिल'} ${s.time?'मिनट':''}</p><h3>वक्ता के लिए</h3><p>${s.speakerCue}</p><h3>संचालन संकेत</h3><p>${s.notes}</p><p><small>${s.source||'चर्चा / अनुप्रयोग'}</small></p>`)}
function overview(){dialog(`<h2>कार्यशाला की रूपरेखा</h2><p>30 स्लाइड · 105 मिनट · हिंदी मुख्य भाषा</p><div class="overview-grid">${slides.map((s,i)=>`<button data-jump="${i+1}">${String(i+1).padStart(2,'0')} &nbsp; ${clean(s.title)}<br><small>${s.section} · ${s.time} मिनट</small></button>`).join('')}</div>`)}
document.querySelector('#prev').onclick=()=>show(current-1);document.querySelector('#next').onclick=()=>show(current+1);document.querySelector('#notes').onclick=notes;document.querySelector('#overview').onclick=overview;document.querySelector('#map').onclick=()=>show(3);document.querySelector('#print').onclick=()=>window.print();
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{dialog('<h2>पूर्ण स्क्रीन</h2><p>इस ब्राउज़र में F11 दबाकर पूर्ण स्क्रीन खोलें।</p>')}}document.querySelector('#fullscreen').onclick=fullscreen;
panel.querySelector('.close').onclick=()=>panel.close();
document.addEventListener('click',e=>{const jump=e.target.closest('[data-jump]');if(jump){if(panel.open)panel.close();show(Number(jump.dataset.jump)-1)}const b=e.target.closest('[data-timer]');if(b){const timer=b.closest('.timer');if(tick&&activeTimer===timer){stopTimer();return}stopTimer();if(activeTimer!==timer||remaining===0)remaining=Number(b.dataset.timer);activeTimer=timer;b.textContent='रोकें';tick=setInterval(()=>{remaining--;timer.querySelector('output').textContent=format(remaining);if(remaining<=0){stopTimer();b.textContent='समय पूरा • फिर शुरू';}},1000)}const r=e.target.closest('[data-reset]');if(r){stopTimer();activeTimer=r.closest('.timer');remaining=Number(r.dataset.reset);activeTimer.querySelector('output').textContent=format(remaining);activeTimer.querySelector('[data-timer]').textContent='चिंतन टाइमर शुरू'}});
document.addEventListener('keydown',e=>{if(panel.open||e.ctrlKey||e.metaKey||e.altKey||e.target.closest('input,textarea'))return;if(e.key===' '&&e.target.closest('button,a'))return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();show(current+1)}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();show(current-1)}if(e.key==='Home')show(0);if(e.key==='End')show(slides.length-1);if(e.key.toLowerCase()==='n')notes();if(e.key.toLowerCase()==='o')overview();if(e.key.toLowerCase()==='f')fullscreen()});
window.addEventListener('hashchange',()=>show((Number(location.hash.slice(1))||1)-1));show((Number(location.hash.slice(1))||1)-1);
